apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smart-parking-platform
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://github.com/reflection9/smart-parking-watcher.git
    targetRevision: codex/block2-iac-gitops
    path: infra/gitops/platform
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
