apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smart-parking-services
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/reflection9/smart-parking-watcher.git
    targetRevision: codex/block2-iac-gitops
    path: helm/smart-parking
    helm:
      releaseName: smart-parking
  destination:
    server: https://kubernetes.default.svc
    namespace: smart-parking
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
